using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BanqueTardiApp.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedID : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ComptesBancaires_Clients_ClientCode",
                table: "ComptesBancaires");

            migrationBuilder.DropForeignKey(
                name: "FK_Transaction_ComptesBancaires_CompteBancaireNumeroCompte",
                table: "Transaction");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Transaction",
                table: "Transaction");

            migrationBuilder.DropIndex(
                name: "IX_Transaction_CompteBancaireNumeroCompte",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "CompteBancaireNumeroCompte",
                table: "Transaction");

            migrationBuilder.RenameTable(
                name: "Transaction",
                newName: "Transactions");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Transactions",
                table: "Transactions",
                column: "Identifiant");

            migrationBuilder.CreateIndex(
                name: "IX_Transactions_NumeroCompte",
                table: "Transactions",
                column: "NumeroCompte");

            migrationBuilder.AddForeignKey(
                name: "FK_ComptesBancaires_Clients_ClientCode",
                table: "ComptesBancaires",
                column: "ClientCode",
                principalTable: "Clients",
                principalColumn: "Code",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Transactions_ComptesBancaires_NumeroCompte",
                table: "Transactions",
                column: "NumeroCompte",
                principalTable: "ComptesBancaires",
                principalColumn: "NumeroCompte",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ComptesBancaires_Clients_ClientCode",
                table: "ComptesBancaires");

            migrationBuilder.DropForeignKey(
                name: "FK_Transactions_ComptesBancaires_NumeroCompte",
                table: "Transactions");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Transactions",
                table: "Transactions");

            migrationBuilder.DropIndex(
                name: "IX_Transactions_NumeroCompte",
                table: "Transactions");

            migrationBuilder.RenameTable(
                name: "Transactions",
                newName: "Transaction");

            migrationBuilder.AddColumn<string>(
                name: "CompteBancaireNumeroCompte",
                table: "Transaction",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Transaction",
                table: "Transaction",
                column: "Identifiant");

            migrationBuilder.CreateIndex(
                name: "IX_Transaction_CompteBancaireNumeroCompte",
                table: "Transaction",
                column: "CompteBancaireNumeroCompte");

            migrationBuilder.AddForeignKey(
                name: "FK_ComptesBancaires_Clients_ClientCode",
                table: "ComptesBancaires",
                column: "ClientCode",
                principalTable: "Clients",
                principalColumn: "Code");

            migrationBuilder.AddForeignKey(
                name: "FK_Transaction_ComptesBancaires_CompteBancaireNumeroCompte",
                table: "Transaction",
                column: "CompteBancaireNumeroCompte",
                principalTable: "ComptesBancaires",
                principalColumn: "NumeroCompte");
        }
    }
}
